image: docker-registry:80/release_engineering/dotci_docker_builder #name of image to run the build against
command:
  - echo 'this is a command'
plugins:
  - docker_publish:
      repository: docker-registry:80
      name: dockerize/file_sharing_servicee
